### ISSUE TITLE
dist file is created with '-' when module name starts with capital letter

### ISSUE THREAD

**Issue by punknroll** [jvandemo/generator-angularjs-library#28]
Hi,

when your module name is "Your Library" and run gulp afterwards the generated file is 
dist/-your-library.js 

but bower.json still says

"main": ["dist/your-library.js"]

**Comment by DenisOS** [comment]
Yeah, I see that too. Not what I wanted. I believe its happening approx line 129 in /app/index.js on this line: 
 dasherized: this._.dasherize(props.libraryName)
This is used to set various folders approx line 145 e.g.
 this.props.librarySrcDirectory = 'src' + '/' + this.props.libraryName.dasherized;
...which are created as folders approx line 178

I believe a fix could to use slugified instead of dasherized on line 145. I will fork and try that.

I'm also checking where comes from so I can confirm why it adds dash at start for upper case. I think its inherited from yeoman.generators.Base.extend ...not clear where from after that.

**Comment by jvandemo** [comment]
Fixed by #33. Thanks @DenisOS!
